### ISSUE TITLE
At least one degenerate class of AA is missing

### ISSUE THREAD

**Issue by Enrique-SC** [HVoltBb/kodonz#1]
Hello, 
I have problems with running the "enc" command in a particular fasta file, appears this legend: "At least one degenerate class of AA is missing, NaN will be produced. Try Fuglsang's formula to get an estimate". Do you know why? How could I fix this?. It worked well with others fasta files.  
Thank you for your help

**Comment by HVoltBb** [comment]
Hi there,
Thanks for using this package.
This warning is related to how Nc is calculated according to Wright's formula. For example, Nc = 2 + 9/F2 + 1/F3 + 5/F4 + 3/F6 for species with the standard codon table, where F2 is the homozygosity of AA with degeneracy 2, and same for F3 to F6. When all the AAs belonging to a degeneracy is missing, the F value for group can not be calculated. So current information is not sufficient to calculate Nc here. You could add more sequence data, and hope the new data are representative of all the degeneracy groups.
Alternatively, I could report the partial Nc value based on what you have right now, but that Nc value would be smaller than what it should be, since you are missing some AA groups.
I recommend collecting more sequence data in this case.

**Comment by Enrique-SC** [comment]
Of course, I see it now! 

Your package has been very useful!  Thank you!
